---
- name: Loops in Ansible
  hosts: all
  tasks:
    - name: Add users to the system
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.group }}"
        create_home: "{{ item.home }}"
      loop:
        - { name: user1, home: false, group: wheel }
        - { name: user2, home: true, group: wheel }
        - { name: user3, home: true, group: wheel }
      when: ansible_facts["os_family"] == "RedHat"
